# Generated by Django 3.1.5 on 2022-01-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_verse_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='author',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verse',
            name='book_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verse',
            name='genre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verse',
            name='page_number',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
