# Generated by Django 3.1.5 on 2022-01-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220118_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
