# Generated by Django 3.1.5 on 2022-03-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220127_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='audited',
            field=models.BooleanField(default=False),
        ),
    ]
