# Generated by Django 3.1.5 on 2022-03-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_verse_audited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verse',
            old_name='audited',
            new_name='verified',
        ),
    ]
