# Generated by Django 3.1.5 on 2022-04-21 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 15, 14, 13, 945146, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
