# Generated by Django 3.1.5 on 2022-04-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_total_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='rules',
            field=models.IntegerField(default=0),
        ),
    ]
