# Generated by Django 3.1.5 on 2022-04-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_total_rules'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['date'], name='date_idx'),
        ),
    ]
