# Generated by Django 3.1.5 on 2022-07-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220719_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('a', 'default'), ('b', 'hayden:default'), ('c', 'hayden:main'), ('d', 'hayden:stacks')], max_length=1)),
                ('text', models.CharField(max_length=1000)),
                ('step', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='rules',
            name='location',
        ),
    ]
