# Generated by Django 3.1.5 on 2022-07-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220720_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='location',
            field=models.CharField(choices=[('a', 'default'), ('b', 'hayden:default'), ('c', 'hayden:main'), ('d', 'hayden:stacks')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
